USE GroundhogBus
CREATE TABLE BusDriverCertification (
    DLN VARCHAR(50) NOT NULL UNIQUE,
    BLPN VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (DLN) REFERENCES BusDriver (DLN),
    FOREIGN KEY (BLPN) REFERENCES Bus (BLPN)
);
